config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :employees
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users
  
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 # root "employees#index"

 
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
	  has_one_attached :files
	  has_one_attached :image

      validates :Employe_type,:skills, presence: true
	 #validates :photos, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg']}

#      validate :correct_document_mime_type

# private
#   def correct_document_mime_type
#     if document.attached? && !document.content_type.in?(%w(application/msword application/pdf))
#       errors.add(:document, 'Must be a PDF or a DOC file')
#     end
#    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_user!
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def index
	@employees= Employee.all
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employees_params)
    respond_to do |format|    
     if @employee.save
       format.js  
       #redirect_to root_path, notice:"submitted success"
     else
       render :new
     end
   end
  end

  def show
    @employee = Employee.find(params[:id])
    
  end

 
  def edit
   @employee = Employee.find(params[:id])
  end


 def update
   @employee =Employee.find(params[:id])
      if @employee.update(employees_params)
          redirect_to root_path
      else
          render :edit
      end


 end
    
  def destroy
    @employee =Employee.find(params[:id])
    @employee.destroy
    redirect_to root_path

  end


  def employees_params
      params.require(:employee).permit(:name,:email,:date_of_birth,:Employe_type,:Technology ,:description, :skills,:gender,:image,:files)       
   end




end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/employees/_form.html.erb
<b><%= link_to "home", root_path %></b>


<center><h1>Employee_details<h1/></center>
  <div class="container">
  
   <%= form_with model: @employee, local:false do |f| %>

  <div class="field form-group">
    <%= f.label :"name" %><br> 
    <%= f.text_field :name ,class:"form-control",:required => true,placeholder:"name" %>

    <% @employee.errors.full_messages_for(:name).each do |message| %>
       <div><%=message%></div>
    <% end %>


  </div><br>

  <div class="field form-group">
    <%= f.label :"email" %><br> 
    <%= f.text_field :email ,class:"form-control",:required => true,placeholder:"email" %>
    
     <% @employee.errors.full_messages_for(:email).each do |message| %>
        <div><%=message%></div>
      <% end %>

  </div><br>

  <div class="field form-group">
    <%= f.label :"date_of_birth" %>
    <%= f.date_field :date_of_birth ,class:"form-control",:required => true,placeholder:"Date for Workout" %>
    
    <% @employee.errors.full_messages_for(:date_of_birth).each do |message| %>
       <div><%=message  %></div>
    <% end %>

  </div><br>

  <div class="field form-group">
    <%= f.label :gender, "Male"%>
    <%= f.radio_button :gender,"male",:required => true %>

    <%= f.label :gender, "Female" %>
    <%= f.radio_button :gender, "female",:required => true %>

    <% @employee.errors.full_messages_for(:gender).each do |message| %>
    <div><%=message  %></div>
     <% end %>

  </div><br>


  <div class="field form-group">
    <%= f.label :Employe_type%>:
    <%=f.select :Employe_type,[['Select'],['Exeperience','exeperience'],['Fresher','fresher']],:required => true%> <br/>

   
   <% @employee.errors.full_messages_for(:Employe_type).each do |message| %>
        <div><%=message %></div>
     <% end %>

  </div><br>

<div id="abc">
  
  <div class="field form-group">
    <%= f.label :Technology %>
    <%=f.select :Technology,[['Select'],['ROR','ror'],['Phython','python'],['React','react']] %><br/>

     <% @employee.errors.full_messages_for(:Technology).each do |message| %>
     <div><%=message%></div>
     <% end %>


  </div><br>

   <div class="field form-group">
    <%= f.label :description %>
    <%= f.text_field :description ,class:"form-control",placeholder:"Description"%>

    <% @employee.errors.full_messages_for(:description).each do |message| %>
      <div><%=message  %></div>
    <% end %>
  </div><br>
</div>
<div class="field form-group">
    <%= f.label :"Skills" %><br> 
    <%= f.text_area :skills ,class:"form-control",placeholder:"Skills",:required => true%>
</div><br>
   
   
   <div class="field form-group" >
    <%= f.label :Passport_image %>
    <%= f.file_field :image,class:"form-control",accept:'.jpeg',placeholder:"Passport_image",:required => true %>
   </div><br>

   <div class="field form-group" >
    <%= f.label :Upload_Resume %>
    <%= f.file_field :files, class:"form-control",placeholder:"Upload_resume",accept:'.doc',:required => true %>
   </div><br>

  <div id="form">
    <%= f.submit class: "btn btn-primary", id: "bt" %> 
  </div>
</div>

<%end%>

<script type="text/javascript">
$(document).ready(function(){
  $("#employee_Employe_type").click(function(){
    a = $("#employee_Employe_type").val();
    if (a=='fresher') {
      $("#abc").hide()
    }
    else{
      $("#abc").show()
    }
  });

});

// $(document).ready(function(){
//   $("#bt").click(function(){
//     a=$("#bt").val()
//     alert("Record submitted successfully");

//   });
// });


</script> 

app/views/employees/create.js.erb
alert("success");
location.reload();

app/views/employees/edit.html.erb
<%= render "form",Employee: @employee %>

app/views/employees/index.html.erb
<hr>
  <h1>Registered candidate-</h1>

<ul>
  <% @employees.each do |employee| %>
    <li>
      <%=link_to employee.name,employee_path(employee)%>
    </li>

  <% end %>
</ul>

	<b><%= link_to "new registraion", new_employee_path %></b>

<hr>

app/views/employees/new.html.erb
<%= render "form",Employee: @employee %>

app/views/employees/show.html.erb
<h1>Employee_details</h1>
<hr>

<p>Name  -<%= @employee.name %></p>
<p>Email -<%= @employee.email%></p>
<p>Gender -<%= @employee.gender%></p>
<p>Date_of_birth -<%= @employee.date_of_birth%></p>
<p>Employee_type-  <%= @employee.Employe_type%></p>
<p>Technology-  <%= @employee.Technology%></p>
<p>Description-  <%= @employee.description%></p>
<p>Passport image- </p>

<%=image_tag(@employee.image , width:120)%> <br/>
<p>Skills-  <%= @employee.skills %></p>




<p>Resume-  <%= @employee.files%></p>

<%= link_to "Edit", edit_employee_path(@employee) %>
<%= link_to "Destroy", employee_path(@employee),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>RailsBootstrap4Integration</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <nav class="navbar navbar-dark bg-primary">

         <h1>Yuvasoft</h1>


   </nav>
   
  </head>

  <body>
  
</ul>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>

    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello!</h1>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>|
  <%= link_to "new registraion", new_employee_path %>|
  <%= link_to "Show Employes", employees_path %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>